Validation array with at least
kaliberjs/forms pull request #20
Opened 2021-04-02 11:42 UTC by peeke

This PR: 

- Adds the `arrayWithAtLeast` validation rule, since this is a pretty common rule;
- Adds an example to demonstrate this rule;

2021-04-06 08:21 UTC, EECOLOR requested changes
Waardevolle toevoeging wat betreft het voorbeeld. Ik zou alleen `arrayWithAtLeast` niet willen toevoegen, maar simpelweg `minLength` gebruiken.

In sommige gevallen resulteert dit in lelijke code:

```js
x => minLength(1)(x) && error('myCustomError')
```

Dat kan echter beter op een andere manier worden opgelost door bij de error afhandeling ook het `field` mee te geven om een onderscheid te kunnen maken voor verschillende errors.

Dus zoiets:

```js
if (error === 'minLength' && field === fields.mySpecialArrayField) ...
else ...
```

2021-04-06 08:21 UTC, EECOLOR commented on src/validation.js
> +
Wat mij betreft gebruik je `minLength`

```suggestion
```

2021-04-06 08:21 UTC, EECOLOR commented on example/src/domain/machinery/Form.js
> +      )}
```suggestion
      {determineIndicator(state)}
```

En dan los in het bestand:

```js
function determineIndicator(state) {
  const { showError, error, invalid, isVisited, isSubmitted, hasFocus } = state
  return (
    (hasFocus || isVisited || isSubmitted) && !invalid ? '✓' :
    hasFocus ? '-' :
    (isVisited || isSubmitted) && invalid && 'x'
   )
}
```

Dan kun je die op beide plekken gebruiken.

2021-04-06 08:21 UTC, EECOLOR commented on example/src/domain/machinery/Form.js
> +            id={`${name}__${i}`}
`htmlFor` en `id` moeten overeen komen.

```suggestion
      {options.map((option, i) => {
        const id = `${name}__${i}`
        return (
          <div key={id}>
            <label htmlFor={id}>{option.label}</label>
            <input
              {...{ id } }
```

2021-04-06 08:21 UTC, EECOLOR commented on example/src/domain/machinery/Form.js
> +            checked={Boolean(value) && value.includes(option.value)}
```suggestion
            checked={Array.isArray(value) && value.includes(option.value)}
```

2021-04-06 08:21 UTC, EECOLOR commented on example/src/domain/machinery/Form.js
> +            onChange={handleChange}
```suggestion
            onChange={handleChange(option.value)}
```

2021-04-06 08:21 UTC, EECOLOR commented on example/src/domain/machinery/Form.js
> +}
Op deze manier zijn we niet afhankelijk van de 'toString' functie van de optie. Dus de value van de optie komt 1 op 1 terug in de `onChange` zonder dat die per ongeluk veranderd is doordat ie via `e.currentTarget.value` binnenkomt.

```suggestion
  function handleChange(changedValue) {
    return e => {
      const newValue =
        !Array.isArray(value) ? [changedValue] : 
        value.includes(changedValue) ? value.filter(x => x !== changedValue) :
        value.concat(changedValue)

      onChange(newValue)
    }
  }
}
```

2021-04-06 08:21 UTC, EECOLOR commented on example/src/domain/Full.js
> +import { optional, required, minLength, arrayWithAtLeast, error, email } from '@kaliber/forms/validation'
```suggestion
import { optional, required, minLength, error, email } from '@kaliber/forms/validation'
```

2021-04-06 08:21 UTC, EECOLOR commented on example/src/domain/Full.js
> +  gevondenVia: [required, arrayWithAtLeast(1)],
```suggestion
  gevondenVia: [required, minLength(1)],
```

2021-04-06 08:21 UTC, EECOLOR commented on validation.js
> +  arrayWithAtLeast,
```suggestion
```

2022-05-09 09:29 UTC, merged

2022-05-09 09:30 UTC, peeke commented
@EECOLOR Hier hoeven we geen versie voor te releasen right? Als je op github de examples checkt doe je dat over het algemeen op de master branch.

2022-05-10 07:43 UTC, EECOLOR commented
@peeke Klopt